# Generated by Django 5.1.1 on 2026-01-15 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_booking_end_date_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 15)),
            preserve_default=False,
        ),
    ]
