# Generated by Django 5.1.1 on 2026-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
