# Generated by Django 5.1.1 on 2026-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_for_other',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest_full_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest_phone',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
