# Generated by Django 5.1.1 on 2026-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
