# Generated by Django 5.1.1 on 2026-03-30 11:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('uk', 'UK'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('uk', 'UK'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('uk', 'UK'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
