# Generated by Django 5.1.1 on 2026-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blogpost_country_section_country_tour_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(default='MAD', max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(choices=[('morocco', 'Morocco'), ('ireland', 'Ireland')], default='morocco', max_length=10),
        ),
    ]
