# Generated by Django 5.1.1 on 2026-03-30 12:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tour_currency_alter_blogpost_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('morocco', 'Morocco'), ('ireland', 'Ireland')], max_length=10, unique=True)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(max_length=255)),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
