# Generated by Django 5.1.1 on 2026-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_countrycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='currency',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='country',
            field=models.CharField(default='morocco', max_length=50),
        ),
        migrations.AlterField(
            model_name='countrycontent',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='countrycontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/heroes/'),
        ),
        migrations.AlterField(
            model_name='countrycontent',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='countrycontent',
            name='hero_title',
            field=models.CharField(default='Discover Morocco', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='country',
            field=models.CharField(default='morocco', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(default='morocco', max_length=50),
        ),
    ]
