# Generated by Django 5.1.1 on 2026-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, help_text='What is included (one item per line).'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included',
            field=models.TextField(blank=True, help_text='What is NOT included (one item per line).'),
        ),
    ]
