# Generated by Django 5.1.1 on 2026-04-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tour_included_tour_not_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='base_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extras_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='include_hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='include_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='selected_extra_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transport_price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: hotel add-on price per night per person.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='transport_price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: transport add-on price per night per person.', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='TourExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_per_night', models.BooleanField(default=False, help_text='If enabled, the price is charged per night per person. Otherwise per trip per person.')),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_activities', to='core.tour')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
