# Generated by Django 5.1.1 on 2026-04-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reservation_base_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card Payment')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
