# Generated by Django 5.1.1 on 2026-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug (auto-generated).', max_length=255, null=True, unique=True),
        ),
    ]
