# Generated by Django 5.1.1 on 2026-04-08 19:38

from django.db import migrations


def _slugify_unique(apps, tour_model, *, raw: str, pk: int | None = None) -> str:
    from django.utils.text import slugify

    base = slugify(raw) or 'tour'
    slug = base
    i = 2
    while tour_model.objects.filter(slug=slug).exclude(pk=pk).exists():
        slug = f"{base}-{i}"
        i += 1
    return slug


def forwards(apps, schema_editor):
    Tour = apps.get_model('core', 'Tour')
    Destination = apps.get_model('core', 'Destination')

    # Populate slug for existing tours where it's missing.
    for tour in Tour.objects.all().select_related('destination'):
        if getattr(tour, 'slug', None):
            continue
        dest_name = ''
        try:
            dest = getattr(tour, 'destination', None)
            dest_name = getattr(dest, 'name', '') or ''
        except Exception:
            dest_name = ''

        raw = f"{dest_name}-{tour.title}" if dest_name else str(tour.title)
        tour.slug = _slugify_unique(apps, Tour, raw=raw, pk=tour.pk)
        tour.save(update_fields=['slug'])


def backwards(apps, schema_editor):
    Tour = apps.get_model('core', 'Tour')
    Tour.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tour_slug'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
