# Generated by Django 5.1.1 on 2026-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_touractivity_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touractivity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touractivity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
