# Generated by Django 5.1.1 on 2026-04-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_touractivity_end_time_touractivity_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourItineraryLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_label', models.CharField(help_text='Example: 200 m, 3 min, 12 km', max_length=80)),
                ('transport_mode', models.CharField(choices=[('walk', 'On foot'), ('bus', 'Bus'), ('taxi', 'Taxi'), ('indrive', 'InDrive'), ('tramway', 'Tramway'), ('private', 'Private transport'), ('car', 'Car'), ('other', 'Other')], default='walk', max_length=20)),
                ('transport_label', models.CharField(blank=True, help_text='Optional custom label, for example: On foot, Small boat', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('from_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_legs', to='core.touractivity')),
                ('to_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_legs', to='core.touractivity')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_legs', to='core.tour')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('tour', 'from_activity', 'to_activity')},
            },
        ),
    ]
