# Generated by Django 5.1.1 on 2026-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_touritineraryleg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touractivity',
            options={'ordering': ['day_number', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='touractivity',
            name='day_number',
            field=models.PositiveIntegerField(default=1, help_text='Example: 1 for Day 1, 2 for Day 2.'),
        ),
        migrations.AddField(
            model_name='touractivity',
            name='point_role',
            field=models.CharField(choices=[('regular', 'Regular stop'), ('start', 'Starting point'), ('end', 'Ending point')], default='regular', max_length=20),
        ),
    ]
