# Generated by Django 5.1.1 on 2026-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_touractivity_options_touractivity_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourextraactivity',
            name='insert_into_itinerary',
            field=models.BooleanField(default=False, help_text='If enabled, this extra activity will be inserted into the day itinerary when selected.'),
        ),
        migrations.AddField(
            model_name='tourextraactivity',
            name='itinerary_day_number',
            field=models.PositiveIntegerField(blank=True, help_text='Example: 1 for Day 1, 2 for Day 2.', null=True),
        ),
        migrations.AddField(
            model_name='tourextraactivity',
            name='itinerary_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes used to shift the following itinerary stops.', null=True),
        ),
        migrations.AddField(
            model_name='tourextraactivity',
            name='itinerary_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
